[package]
name = "rdo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {version = "0.13.3", features = ["toml"]}
petgraph = {version = "0.6.3", features = ["serde-1"]}
serde = {version = "1.0.152", features = ["derive"]}
uuid = {version = "1.3.0", features = ["serde", "v4"]}
