name: Bump Tag

on:
  push:
    branches: 'main'

jobs:
  build:
    name: Bump tag
    runs-on: ubuntu-latest

    steps:
      - name: Create an incremental release
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: false
          message: Bump version to ${{ steps.bump.outputs.new_tag }}
          prev_tag: 'v'
          update_odoo_module_version: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}