name: Pre-release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  pre-release:
    name: Pre-release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: cargo build --release --target ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}
      - name: package
        run: |
          mkdir -p release
          for archive in ${{ matrix.archive }}; do
            cmd="tar -cJf release/${{ matrix.target }}.tar.${archive} -C target/${{ matrix.target }}/release/ ."
            echo $cmd
            $cmd
          done
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            README.md
            release/${{ matrix.target }}.tar.gz
            release/${{ matrix.target }}.tar.xz
            release/${{ matrix.target }}.tar.zst