name: Upload Release Asset

on: workflow_dispatch

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: cargo build --verbose --release --target ${{ matrix.target }}
        run: cargo build --verbose --release --target ${{ matrix.target }}
      - name: package
        run: |
          mkdir -p release
          for archive in ${{ matrix.archive }}; do
            tar -cJf release/${{ matrix.target }}.tar.${archive} -C target/${{ matrix.target }}/release/ .
          done
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            README.md
            release/${{ matrix.target }}.tar.gz