name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  tagged-release:
    name: Tagged release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package
        run: |
          mkdir -p release
          for archive in ${{ matrix.archive }}; do
            cmd="tar -cJf release/${{ matrix.target }}.${archive} -C target/${{ matrix.target }}/release/ ."
            echo $cmd
            $cmd
          done
      - uses: "softprops/action-gh-release@v1"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            README.md
            release/${{ matrix.target }}.tar.gz
            release/${{ matrix.target }}.tar.xz
            release/${{ matrix.target }}.tar.zst
          token: ${{ secrets.RELEASE_PAT }}