name: Rust Build/Test

on:
  workflow_call:

jobs:
  build:
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - uses: "nseguin42/rdo/.github/workflows/rust-lint.yaml"
      - name: cargo build --verbose
        run: cargo build --verbose
      - name: cargo test --verbose
        run: cargo test --verbose