name: Rust CI

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tagged-release:
    name: Tagged release ${{ matrix.target }}
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --locked
      - uses: ./.github/workflows/bump-tag.yaml
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Package
        run: |
          mkdir -p release
          for archive in ${{ matrix.archive }}; do
            cmd="tar -cJf release/${{ matrix.target }}.${archive} -C target/${{ matrix.target }}/release/ ."
            echo $cmd
            $cmd
          done
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            README.md
            release/${{ matrix.target }}.tar.gz
            release/${{ matrix.target }}.tar.xz
            release/${{ matrix.target }}.tar.zst
          token: ${{ secrets.RELEASE_PAT }}