name: Rust Build/Test

on:
  workflow_call:
    secrets:
      release_pat:
        description: 'GitHub PAT to use for releases'
        required: true

jobs:
  build:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: ./.github/workflows/rust-lint.yaml
      - name: cargo build --verbose
        run: cargo build --verbose
      - name: cargo test --verbose
        run: cargo test --verbose