name: Rust CI (main, build)

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: needs.check.outputs.should_skip != 'true' || !fromJSON(needs.check.outputs.paths_result).build.should_skip
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --locked
      - name: Package
        run: |
          mkdir -p release
          cmd="tar -cJf release/${{ matrix.target }}.${archive} -C target/release/ ."
          echo $cmd
          $cmd
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: main-release-artifacts
          path: |
            release/${{ matrix.target }}.*
            LICENSE
            README.md
  tagged-release:
    name: Tagged release ${{ matrix.target }}
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p release
      - uses: actions/download-artifact@v3
        with:
          name: main-release-artifacts
          path: release
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*
          token: ${{ secrets.RELEASE_PAT }}
          tag: ${{ github.ref }}