name: Rust CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_ci_dev_build:
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/rust-ci-dev-build.yaml

  rust_ci_main_build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/rust-ci-main-build.yaml
    secrets: inherit

  rust_ci_main_release:
    needs: [ rust_ci_main_build ]
    uses: ./.github/workflows/rust-ci-main-release.yaml
    secrets: inherit