name: Rust CI (main, release)
on:
  workflow_run:
    workflows: [ "Rust CI (main, build)" ]
    types:
      - completed


env:
  CARGO_TERM_COLOR: always

jobs:
  tagged-release:
    name: Tagged release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst

    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p release
      - uses: actions/download-artifact@v3
        with:
          name: main-release-artifacts
          path: release
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*
          token: ${{ secrets.RELEASE_PAT }}
          tag: ${{ inputs.tag_name }}