name: Rust CI

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  startup:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["push"]'
          paths_ignore: '[ "README.md", "LICENSE", ".gitignore", ".github/**", ".rustfmt.toml" ]'
          paths_filter: |
            build:
              paths:
                - Cargo.toml
                - Cargo.lock
                - src/**
                - tests/**

  tagged-release:
    needs: startup
    name: Tagged release ${{ matrix.target }}
    if: startsWith(github.ref, 'refs/tags/') && (needs.check.outputs.should_skip != 'true' || !fromJSON(needs.check.outputs.paths_result).build.should_skip)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --locked
      - uses: ./.github/workflows/bump-tag.yaml
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Package
        run: |
          mkdir -p release
          for archive in ${{ matrix.archive }}; do
            cmd="tar -cJf release/${{ matrix.target }}.${archive} -C target/${{ matrix.target }}/release/ ."
            echo $cmd
            $cmd
          done
      - name: Create an incremental release
        uses: aurestic/incremental-create-release@master
        with:
          flag_branch: false
          message: Bump version to ${{ steps.bump.outputs.new_tag }}
          prev_tag: 'v'
          update_odoo_module_version: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            README.md
            release/${{ matrix.target }}.tar.gz
            release/${{ matrix.target }}.tar.xz
            release/${{ matrix.target }}.tar.zst
          token: ${{ secrets.RELEASE_PAT }}